apiVersion: v1
kind: Service
metadata:
  name: meu-blog-escalavel-service
spec:
  type: NodePort # (LoadBalancer, NodePort, ClusterIP) Expor porta para fora do meu cluster
  selector:
    app: wordpress-escalavel
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80